### ISSUE TITLE
docs(README): sqlx-cli installation

### ISSUE THREAD

**Issue by ghost** [RainingComputers/Flowmium#1]
### Problem Statement

Following the `README.md` instructions and running `make up && make test` will result in `make test` failing with `sqlx` command not found.

### Recommended Solution

Make reference to how users or contributors can run something like `cargo install sqlx-cli` to ensure `Makefile commands do not fail with command not found failures.

### Resources

https://github.com/launchbadge/sqlx/blob/main/sqlx-cli/README.md#install

**Comment by RainingComputers** [comment]
This has been fixed 👍
