### ISSUE TITLE
docs(OSX): 403 Error on localhost:5000

### ISSUE THREAD

**Issue by ghost** [RainingComputers/Flowmium#2]
### Problem Statement

Running `make test` after following instructions from `README.md` can result in the following errors:

```shell
make test
...
docker tag flowmium-debug localhost:5000/flowmium-debug:latest
docker push localhost:5000/flowmium-debug:latest
The push refers to repository [localhost:5000/flowmium-debug]
Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused
make: *** [test] Error 1
```

### Recommended Solution

Change the default port of 5000 or disable Airplay Receiver. Follow instructions references in resources for more details.

### Resources

- [localhost:5000 unavailable in macOS v12 (Monterey)](https://stackoverflow.com/questions/69818376/localhost5000-unavailable-in-macos-v12-monterey)

**Comment by RainingComputers** [comment]
I have changed the port to 5180, you can now run tests on macOS 👍
